
/**
 * WARNING: DO NOT EDIT THIS FILE
 *
 * This source file was generated from the CPlusPlusGenerator.xsl stylesheet
 *
 * Your changes will be overwritten when this tool executes again.  In order
 * to edit the contents, you must go into the source XML files
 *
 * @author Greg Baumgardner
 */
 

#ifndef INCLUDE_APPLICATIONDATAMESSAGEENUMTYPES_H_
#define INCLUDE_APPLICATIONDATAMESSAGEENUMTYPES_H_

#ifndef CONSTEXPR
#if __cplusplus > 199711L
#define CONSTEXPR constexpr
#else
#ifdef __GNUC__
#define CONSTEXPR __attribute__ ((unused))
#else
#define CONSTEXPR
#endif /* __GNUC__ */
#endif /* __cplusplus > 199711L */
#endif

#if __cplusplus >= 201103L
#include <tmx/utils/Enum.hpp>
#endif /* __cplusplus >= 201103L */
		
	
namespace tmx {
	
		
namespace messages {
	
			
namespace appdatamessage {
	
				
enum DataCodeId 
{
		NOEVENTID = 0,
		EPCW = 1,
		VTRW = 2
};
		
static CONSTEXPR const char *DATACODEID_NOEVENTID_STRING = "None";
static CONSTEXPR const char *DATACODEID_EPCW_STRING = "EPCW";
static CONSTEXPR const char *DATACODEID_VTRW_STRING = "VTRW";
		
static CONSTEXPR const char *DATACODEID_ALL_STRINGS[] = 
{
		DATACODEID_NOEVENTID_STRING,
		DATACODEID_EPCW_STRING,
		DATACODEID_VTRW_STRING
};
		
enum StageTypes 
{
		None = 0,
		Detected = 1,
		Entering = 2,
		InCenter = 3,
		Exiting = 4
};
		
static CONSTEXPR const char *STAGETYPES_NONE_STRING = "None";
static CONSTEXPR const char *STAGETYPES_DETECTED_STRING = "Detected";
static CONSTEXPR const char *STAGETYPES_ENTERING_STRING = "Entering";
static CONSTEXPR const char *STAGETYPES_INCENTER_STRING = "InCenter";
static CONSTEXPR const char *STAGETYPES_EXITING_STRING = "Exiting";
		
static CONSTEXPR const char *STAGETYPES_ALL_STRINGS[] = 
{
		STAGETYPES_NONE_STRING,
		STAGETYPES_DETECTED_STRING,
		STAGETYPES_ENTERING_STRING,
		STAGETYPES_INCENTER_STRING,
		STAGETYPES_EXITING_STRING
};
		
			
} /* End namespace appdatamessage */
		
		
} /* End namespace messages */
		
	
} /* End namespace tmx */
		

#if __cplusplus >= 201103L
		
#endif /* __cplusplus >= 201103L */ 
#endif /* INCLUDE_APPLICATIONDATAMESSAGEENUMTYPES_H_ */
	